spring.application.name=FoodApp

# MySQL Database Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/fooddb
spring.datasource.username=root
spring.datasource.password=MyNewPassword_2026!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# PostgreSQL Database Configuration
# ==========================================

#spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
#spring.datasource.username=postgres
#spring.datasource.password=your_postgres_password
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect